### PR TITLE
BUGFIX: Polygon and multipolygon fromWkt fix

### LINKED ISSUE #37: Polygon.fromWKT throws RangeError
Hello. I believe there's a problem with the `Polygon.fromWKT` method.

Going through the Wikipedia page for Well-Known Text, specifically the [geometries section](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Geometric_objects), shows an example of the Polygon geometry as `POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))`. However, the `Polygon.fromWKT` method seems to crash when trying to parse this.

Upon reviewing the implementation, I identified two potential issues:

1. The method splits on ( and ), but a Polygon geometry uses (( and )).
2. The map lambda calls `Coordinate.fromWKT`, but it throws an error due to the spaces after the commas.

Here's a code sample for your convenience:
```dart

import 'package:geodart/geometries.dart';

main() {
  final wkt = 'POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))';
  
  // uncomment to see the error
  //print(Polygon.fromWKT(wkt));
  
  print(fixedPolygonFromWKT(wkt));
}

Polygon fixedPolygonFromWKT(String wkt) {
  // (( instead of ( and )) instead of )
  final coordinates = wkt.split('((')[1].split('))')[0].split(',');
  // c.trim() instead of c, as the spaces after commas seem to cause problems as well
  return Polygon(
      [LinearRing(coordinates.map((c) => Coordinate.fromWKT(c.trim())).toList())]);
}

```
The `fixedPolygonFromWKT` function should be a drop-in replacement for `Polygon.fromWKT` to address these issues. However, there may be edge cases that I missed, so it would be great if you could review the specification as well.

Thank you for your package, and have a nice day!

### PR DESCRIPTION
**Pull request by ntatko**
Resolves #37 

Thanks to @RMZeroFour for proposing a solution.

### CODE REVIEW

File: lib/src/featureTypes/multi_polygon.dart [hunk 1]
```diff
@@ -95,16 +95,15 @@ class MultiPolygon extends Feature {
   /// ```
   @override
   factory MultiPolygon.fromWKT(String wkt) {
-    final polygonType = wkt.matchAsPrefix('MULTIPOLYGON');
-    if (polygonType == null) {
+    final polygonType = wkt.startsWith('MULTIPOLYGON');
+    if (!polygonType) {
       throw ArgumentError('wkt is not a MultiPolygon');
     }
```
Comment (RMZeroFour) [inline lib/src/featureTypes/multi_polygon.dart:101]: I think this startsWith check should be added to Polygon.fromWKT too for consistency.

**Comment by RMZeroFour** [comment]
Seems good to me otherwise! I tested the changed methods for a few different cases, and they all passed without issues.

File: lib/src/featureTypes/multi_polygon.dart (hunk 1 above)
Comment (ntatko) [reply lib/src/featureTypes/multi_polygon.dart:101]: Done!
